#pragma once
#ifndef HEADER_H
#define HEADER_H
#include <iostream>
#include <iomanip>
#include <string>
#include <algorithm>
#include <time.h>
#include <limits>
#include <vector>
#include <fstream>
#include <sstream>
#include <chrono>
#include <cstdio>
#include <list>
#include <iterator>
using std::cout;
using std::cin;
using std::endl;
using std::left;
using std::right;
using std::setw;
using std::setprecision;
using std::string;
using std::copy;
using std::sort;
using std::fixed;
using std::numeric_limits;
using std::streamsize;
using std::exception;
using std::vector;
using std::invalid_argument;
using std::ifstream;
using std::ofstream;
using std::getline;
using std::noskipws;
using std::istringstream;
using std::list;
#endif